### ISSUE TITLE
mpu 6050

### ISSUE THREAD

**Issue by giohomer** [honnet/twi#1]
hi. I'm a student and i need to work with mpu 6050 ( Gy-521 module ) and nrf51822chip.
So i have some problem to comunicate with 6050 via TWI.
Can you help me?
I have the softdevice enabled

**Comment by honnet** [comment]
Did you see the following projetcs ?
http://github.com/Seeed-Studio/ble_smurfs
http://github.com/NordicSemiconductor/puck/blob/a8b1d08462de73140bfbddcb19c4ddf4225514df/_tutorials/cube.md
Good luck ;)

**Comment by honnet** [comment]
Hey @giohomer,
I published this: https://github.com/medialablasalle/twiz
It's not finished but you can play with it ;)
