### ISSUE TITLE
ble and imu firmware

### ISSUE THREAD

**Issue by new2** [honnet/twi#2]
Hello! I came across your project on http://www.hackster.io/cedric/twi and it looks really interesting. I see you mentioned that the software and hardware are open source. Thanks for doing that btw!

I am thinking of ordering a few boards but I am not that well versed in ble and imu. Do you plan on open sourcing the ble ( nordic ) and imu ( mpu ) firmware to run the board ?

**Comment by honnet** [comment]
Hey,
It's planned but not ready, you might be interested by these repositories:
https://github.com/RedBearLab/nRF51822-Arduino
https://github.com/kriswiner/MPU-9150
Good luck ;)

**Comment by new2** [comment]
Thanks! I will definitely check out those repos. If it's any help, even semi-working would be great to run on the board. I plan on ordering from the pcb manufacturer you mentioned. Either way, great job. :+1:

**Comment by honnet** [comment]
Hey @new2,
I published this: https://github.com/medialablasalle/twiz
It's not finished but you can play with it ;)

**Comment by new2** [comment]
Awesome! Thank you. I will check it out today :)
